const GET_USERS_SAGA = "GET_USERS_SAGA";
const SET_USERS = "SET_USERS";
const GET_TOKEN_SAGA = "GET_TOKEN_SAGA";
const REGISTER_USER_SAGA = "REGISTER_USER_SAGA";
const GET_TWEET_SCORES_SAGA = "GET_TWEET_SCORES_SAGA";
const SET_TOKEN = "SET_TOKEN";
const SET_USERNAME = "SET_USERNAME";
const SET_TWEET_SCORES = "SET_TWEET_SCORES";

export {
  //eslint-disable-line
  GET_USERS_SAGA,
  SET_USERS,
  GET_TOKEN_SAGA,
  SET_TOKEN,
  SET_USERNAME,
  SET_TWEET_SCORES,
  REGISTER_USER_SAGA,
  GET_TWEET_SCORES_SAGA,
};
