const GET_USERS_SAGA = "GET_USERS_SAGA";
const SET_USERS = "SET_USERS";
const GET_TOKEN_SAGA = "GET_TOKEN_SAGA";
const REGISTER_USER_SAGA = "REGISTER_USER_SAGA";
const GET_TWEET_SCORES_SAGA = "GET_TWEET_SCORES_SAGA";
const GET_FREQUENT_ENTITIES_SAGA = "GET_FREQUENT_ENTITIES_SAGA";
const GET_LATEST_TWEETS_SAGA = "GET_LATEST_TWEETS_SAGA";
const GET_MOST_USED_WORDS_SAGA = "GET_MOST_USED_WORDS_SAGA";
const GET_SEARCH_DATA_SAGA = "GET_SEARCH_DATA_SAGA";
const SET_TOKEN = "SET_TOKEN";
const SET_USERNAME = "SET_USERNAME";
const SET_TWEET_SCORES = "SET_TWEET_SCORES";
const SET_FREQUENT_ENTITIES = "SET_FREQUENT_ENTITIES";
const SET_LATEST_TWEETS = "SET_LATEST_TWEETS";
const SET_MOST_USED_WORDS = "SET_MOST_USED_WORDS";
const SET_SEARCH_DATA = "SET_SEARCH_DATA";

export {
  //eslint-disable-line
  GET_USERS_SAGA,
  SET_USERS,
  GET_TOKEN_SAGA,
  SET_TOKEN,
  SET_USERNAME,
  SET_TWEET_SCORES,
  SET_FREQUENT_ENTITIES,
  SET_LATEST_TWEETS,
  SET_MOST_USED_WORDS,
  SET_SEARCH_DATA,
  REGISTER_USER_SAGA,
  GET_TWEET_SCORES_SAGA,
  GET_FREQUENT_ENTITIES_SAGA,
  GET_LATEST_TWEETS_SAGA,
  GET_MOST_USED_WORDS_SAGA,
  GET_SEARCH_DATA_SAGA,
};
