# Generated by Django 3.1.4 on 2021-01-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovidAnalyzerRestApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='name',
            field=models.CharField(default='test', max_length=4000),
            preserve_default=False,
        ),
    ]
