# Generated by Django 3.1.4 on 2021-01-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovidAnalyzerRestApi', '0003_auto_20210109_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetScore',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('tweet_score', models.IntegerField(default=0, null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
