# Generated by Django 3.1.4 on 2021-01-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CovidAnalyzerRestApi', '0004_tweetscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetscore',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
